apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flashwear-backend-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: api.flashwear.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flashwear-backend-service
            port:
              number: 80
